language: bash
services: docker

env:
    global:
        - RENPY_VERSION="7.2.2"

script:
    - docker build -t codeneko/renpy --build-arg RENPY_VERSION=$RENPY_VERSION .;
      docker tag codeneko/renpy codeneko/renpy:$RENPY_VERSION;

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push codeneko/renpy;
      fi;
